name: Build

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
         - os: windows-latest
           platform: win
           arch: x64
           artifact: 'BetterCrewLink Installer Windows'
         - os: ubuntu-latest
           platform: linux
           arch: x64
           artifact: 'BetterCrewLink Installer Linux'

    steps:
      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libx11-dev
          sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --network-timeout 100000
        
      - name: Build 64-bit App
        run: |
          yarn run electron-builder --${{ matrix.platform }} \
            --config.asar=true \
            --config.artifactName="Better-CrewLink-${VERSION}-${PLATFORM}-${ARCH}.${EXT}" \
            --${{ matrix.arch }} \
            --publish never
        env:
          VERSION: ${{ github.run_number }}
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
          EXT: ${{ matrix.platform == 'win' && 'exe' || 'AppImage' }}
          
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            dist/*.exe
            dist/*.AppImage
          if-no-files-found: error